version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: .dockerfiles/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    links:
      - redis
  web:
    build:
      context: ./
      dockerfile: .dockerfiles/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80
  database:
    image: mariadb
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33061:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"