version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7-fpm
      - image: redis:5.0.2
    steps:
      - checkout
      - run:
          name: 'Creating .env file'
          command: |
            cp .circleci/.env.example .env
      - run:
          name: 'Creating database file'
          command: |
            touch database/test-db.sqlite
      - run:
          name: 'Install Project dependencies'
          command: |
            composer install -v
      - run:
          name: 'Generating application key'
          command: |
            php artisan key:generate
      - run:
          name: 'Creating database schema'
          command: |
            php artisan migrate
      - run:
          name: 'Running PHPCS tests'
          command: |
            ./vendor/bin/phpcs -p ./
      - run:
          name: 'Running PHPUnit tests'
          command: |
            ./vendor/bin/phpunit