version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7-fpm
    steps:
      - run:
          name: 'Installing Redis'
          command: |
            wget http://download.redis.io/redis-stable.tar.gz && tar xvzf redis-stable.tar.gz && cd redis-stable && make
      - run:
          name: 'Starting and testing Redis'
          command: |
            redis-server && redis-cli ping
      - checkout
      - run:
          name: 'Creating .env file'
          command: |
            cp .circleci/.env.example .env
      - run:
          name: 'Creating database file'
          command: |
            touch database/test-db.sqlite
      - run:
          name: 'Install Project dependencies'
          command: |
            composer install -v
      - run:
          name: 'Generating application key'
          command: |
            php artisan key:generate
      - run:
          name: 'Creating database schema'
          command: |
            php artisan migrate
      - run:
          name: 'Running PHPCS tests'
          command: |
            ./vendor/bin/phpcs -p ./
      - run:
          name: 'Running PHPUnit tests'
          command: |
            ./vendor/bin/phpunit