version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7-fpm
    steps:
      - checkout
      - run: cp .circleci/.env.example .env
      - run: composer install -v
      - run: php artisan migrate
      - run:
          name: 'Running Tests'
          command: |
            ./vendor/bin/phpcs -p ./ && ./vendo/bin/phpunit